name: Test

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    name: 🧪 E2E Test (${matrix.shard}/4)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4] # Total de shards definidos manualmente

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Configurando o Node.js para a versão 22

      - name: Install Dependencies
        run: npm ci

      - name: Debug Secrets
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Email: ${EMAIL:0:3}"
          echo "Password: ${PASSWORD:0:3}***" # Mascarando o segredo

      - name: Run E2E Tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npx wdio run ./wdio.conf.ts --shard ${{ matrix.shard }}/4

      # Upload dos relatórios gerados
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.shard }}
          path: reports