name: Test

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    name: 🧪 E2E Test (${matrix.shard}/4)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4] # Total de shards definidos manualmente

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Configurando o Node.js para a versão 22

      - name: Install Dependencies
        run: npm ci

      - name: Run E2E Tests
        run: npx run wdio -- --shard ${{ matrix.shard }}/4

      - name: Upload Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.shard }}
          path: logs
